DATNWEB/Areas/Admin/Controllers/PackageController.cs
using DATNWEB.Models;
using DATNWEB.Models.Authentication;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using X.PagedList;

namespace DATNWEB.Areas.Admin.Controllers
{
    [AuthForAdmin]
    [Area("admin")]
    public class PackageController : Controller
    {
        QlPhimAnimeContext db = new QlPhimAnimeContext();
        [Route("admin/package")]
        [HttpGet]
        public IActionResult PackageList(int? page)
        {
            int pagesize = 10;
            int pagenum = page == null || page < 0 ? 1 : page.Value;
            var a = db.ServicePackages.AsNoTracking().OrderBy(x => x.PackageId);
            PagedList<ServicePackage> lst = new PagedList<ServicePackage>(a, pagenum, pagesize);
            return View(lst);
        }
        [Route("admin/Packageadd")]
        [HttpGet]
        public IActionResult PackagesAdd()
        {
            var PackageWithMaxId = db.ServicePackages.OrderByDescending(x => x.PackageId).FirstOrDefault();
            string id = "SP0001";
            if (PackageWithMaxId != null)
            {
                AutoCode a = new AutoCode();
                id = a.GenerateMa(PackageWithMaxId.PackageId);
            }
            var direc = new ServicePackage() { PackageId = id };
            return View(direc);
        }
        [Route("Packageadds")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult PackageAdds(ServicePackage Package)
        {
            if (ModelState.IsValid)
            {
                db.ServicePackages.Add(Package);
                db.SaveChanges();
                return RedirectToAction("PackageList");
            }
            return View(Package);
        }
        [Route("admin/Packageedit")]
        [HttpGet]
        public IActionResult PackageEdit(string id)
        {
            var a = db.ServicePackages.Where(x => x.PackageId == id).FirstOrDefault();
            return View(a);
        }
        [Route("Packageedit")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult PackageEdits(ServicePackage Package)
        {
            if (ModelState.IsValid)
            {
                db.Entry(Package).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("PackageList");
            }
            return View(Package);
        }
        [Route("Packagedelete")]
        [HttpGet]
        public IActionResult PackageDelete(string id)
        {
            var Packageanimes = db.UserSubscriptions.Where(x => x.PackageId == id).ToList();
            if (Packageanimes.Count() > 0)
            {
                TempData["DeleteError"] = "Can not delete the Service Package!";
                return RedirectToAction("PackageList");
            }
            db.Remove(db.ServicePackages.Find(id));
            db.SaveChanges();
            return RedirectToAction("PackageList");
        }
    }
}

DATNWEB/Controllers/packageController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using DATNWEB.Models;
using Newtonsoft.Json;
namespace DATNWEB.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class packageController : ControllerBase
    {
        QlPhimAnimeContext db = new QlPhimAnimeContext();
        [HttpGet]
        public IActionResult package()
        {
            var sessionInfoJson = HttpContext.Session.GetString("SessionInfo");
            var sessionInfo = JsonConvert.DeserializeObject<dynamic>(sessionInfoJson);
            string userId = sessionInfo.UID;
            var p = db.ServicePackages.ToList();
            var user = db.Users.Find(userId);
            var data = new
            {
                p,
                user
            };
            return Ok(data);
        }
    }
}

DATNWEB/Areas/Admin/Views/Package/PackageEdit.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@model DATNWEB.Models.ServicePackage;
@{
    ViewData["Title"] = "PackageEdit";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="card">
    <div class="card-body">
        <h4 class="card-title">Add Package</h4>
        <form method="post" action="@Url.Action("PackageEdits", "Package")" class="forms-sample">
            @Html.AntiForgeryToken()
            <div class="form-group">
                <label>Package ID</label>
                <input type="text" class="form-control" asp-for="PackageId" placeholder="ID" value="@Model.PackageId" readonly>
            </div>
            <div class="form-group">
                <label>Package Name</label>
                <input type="text" class="form-control" asp-for="PackageName" placeholder="Name" value="@Model.PackageName">
            </div>
            <div class="form-group">
                <label>Information</label>
                <input type="text" class="form-control" asp-for="Description" placeholder="Description" value="@Model.Description">
            </div>
            <div class="form-group">
                <label>Information</label>
                <input type="number" class="form-control" asp-for="ValidityPeriod" placeholder="ValidityPeriod" value="@Model.ValidityPeriod">
            </div>
            <button type="submit" class="btn btn-gradient-primary me-2">Submit</button>
            <a class="btn btn-light" href="/admin/package">Cancel</a>
        </form>
    </div>
</div>

DATNWEB/Areas/Admin/Views/Package/PackageList.cshtml
@using DATNWEB.Models;
@using X.PagedList.Mvc.Core;
@using X.PagedList.Web.Common;
@model X.PagedList.IPagedList<ServicePackage>;
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@{
    ViewData["Title"] = "PackageList";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}
@if (TempData["DeleteError"] != null)
{
    <div class="alert alert-danger" role="alert">
        @TempData["DeleteError"]
    </div>
}
<div class="card mb-4">
    <div class="card-header">
        <div class="d-flex justify-content-between align-items-center">
            <div>
                <i class="fas fa-table me-1"></i>
                <span class="fw-bold">Package List</span>
            </div>
            <div>
                <a class="btn btn-primary" href="/admin/Packageadd">Create New</a>
            </div>
        </div>
    </div>

    <div class="card-body">
        <table class="table table-bordered">
            <thead class="thead-dark">
                <tr>
                    <th>Package ID</th>
                    <th>Package Name</th>
                    <th>Information</th>
                    <th>Price</th>
                    <th>Validity period</th>
                    <th></th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @if (Model.Count == 0)
                {
                    <tr>
                        <td colspan="7" style="text-align: center;">
                            No Data
                        </td>

                    </tr>
                }
                else
                {
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.PackageId)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.PackageName)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Description)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Price)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.ValidityPeriod)
                            </td>
                            <td>
                                <a class="btn btn-primary" asp-action="PackageEdit" asp-route-id="@item.PackageId">Edit</a>
                            </td>
                            <td>
                                <a class="btn btn-danger" asp-action="PackageDelete" asp-route-id="@item.PackageId">Delete</a>
                            </td>
                        </tr>
                    }
                }

            </tbody>
        </table>
        @if (Model.PageCount > 1)
        {
            <div class="datatable-pagination">
                @Html.PagedListPager(Model, page => Url.Action("PackageList", new { page = page }), PagedListRenderOptions.ClassicPlusFirstAndLast)
            </div>
        }
    </div>
</div>

DATNWEB/Areas/Admin/Views/Package/PackagesAdd.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@model DATNWEB.Models.ServicePackage;
@{
    ViewData["Title"] = "PackagesAdd";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="card">
    <div class="card-body">
        <h4 class="card-title">Add Package</h4>
        <form method="post" action="@Url.Action("PackageAdds", "Package")" class="forms-sample">
            @Html.AntiForgeryToken()
            <div class="form-group">
                <label>Package ID</label>
                <input type="text" class="form-control" asp-for="PackageId" placeholder="ID" value="@Model.PackageId" readonly>
            </div>
            <div class="form-group">
                <label>Package Name</label>
                <input type="text" class="form-control" asp-for="PackageName" placeholder="Name">
            </div>
            <div class="form-group">
                <label>Information</label>
                <input type="text" class="form-control" asp-for="Description" placeholder="Description">
            </div>
            <div class="form-group">
                <label>Information</label>
                <input type="number" class="form-control" asp-for="ValidityPeriod" placeholder="ValidityPeriod">
            </div>
            <button type="submit" class="btn btn-gradient-primary me-2">Submit</button>
            <a class="btn btn-light" href="/admin/package">Cancel</a>
        </form>
    </div>
</div>