DATNWEB/Models/Episode.cs
using System;
using System.Collections.Generic;

namespace DATNWEB.Models
{
    public partial class Episode
    {
        public Episode()
        {
            Comments = new HashSet<Comment>();
            Views = new HashSet<View>();
        }

        public string EpisodeId { get; set; } = null!;
        public string? AnimeId { get; set; }
        public string? Title { get; set; }
        public int? Ep { get; set; }
        public DateTime PostingDate { get; set; }
        public string? VideoUrl { get; set; }

        public virtual Anime? Anime { get; set; }
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual ICollection<View> Views { get; set; }
    }
}

DATNWEB/Areas/Admin/Controllers/EpisodeController.cs
using CloudinaryDotNet.Actions;
using CloudinaryDotNet;
using DATNWEB.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using X.PagedList;
using Microsoft.AspNetCore.Mvc.Rendering;
using DATNWEB.Models.Authentication;
using DATNWEB.Hubs;
using Microsoft.AspNetCore.SignalR;
using DATNWEB.Models.ViewModel;
using Hangfire;

namespace DATNWEB.Areas.Admin.Controllers
{
    
    [Area("admin")]
    public class EpisodeController : Controller
    {
        private readonly IHubContext<NotificationHub> _hubContext;
        private readonly IBackgroundJobClient _backgroundJobClient;
        public EpisodeController(IHubContext<NotificationHub> hubContext, IBackgroundJobClient backgroundJobClient)
        {
            _hubContext = hubContext;
            _backgroundJobClient = backgroundJobClient;
        }
        private HttpClient httpClient = new HttpClient();
        QlPhimAnimeContext db = new QlPhimAnimeContext();
        [AuthForAdmin]
        [Route("admin/Episode")]
        [HttpGet]
        public IActionResult EpisodeList(string id ,int? page)
        {
            int pagesize = 10;
            int pagenum = page == null || page < 0 ? 1 : page.Value;
            var a = db.Episodes.AsNoTracking().OrderBy(x => x.EpisodeId).Where(x=>x.AnimeId == id);
            PagedList<Episode> lst = new PagedList<Episode>(a, pagenum, pagesize);
            ViewBag.AnimeId = id;
            return View(lst);
        }
        [AuthForAdmin]
        [Route("admin/Episodeadd")]
        [HttpGet]
        public IActionResult EpisodesAdd(string ani)
        {
            var EpisodeWithMaxId = db.Episodes.OrderByDescending(x => x.EpisodeId).FirstOrDefault();
            var epmax = db.Episodes.OrderByDescending(x => x.EpisodeId).Where(x => x.AnimeId == ani).FirstOrDefault();
            string id = "EP0001";
            int? ep = 0;
            if (EpisodeWithMaxId != null)
            {
                AutoCode a = new AutoCode();
                id = a.GenerateMa(EpisodeWithMaxId.EpisodeId);
                
            }
            if(epmax != null)
            {
                ep = epmax.Ep + 1;
            }
            var direc = new Episode() { EpisodeId = id , AnimeId = ani, Ep = ep};
            return View(direc);
        }
        [AuthForAdmin]
        [Route("Episodeadds")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EpisodesAdd(Episode Episode, IFormFile video)
        {
            if (ModelState.IsValid)
            {
                Account account = new Account(
                    "dbpbkj4pg",
                    "718584524965961",
                    "exe6MST-mc9nLkpubAWeazM7gLI");
                Cloudinary cloudinary = new Cloudinary(account);
                cloudinary.Api.Secure = true;

                httpClient.Timeout = TimeSpan.FromMinutes(10);
                using (var hStream = video.OpenReadStream())
                {
                    var hUploadParams = new VideoUploadParams()
                    {
                        File = new FileDescription(video.FileName, hStream),
                        PublicId = "DATN/Anime/" + Episode.AnimeId.ToString() + "/Episode/ep" + Episode.Ep.ToString()+"/"+Episode.Ep.ToString()+Episode.AnimeId.ToString(),
                        Overwrite = true,
                    };
                    var hUploadResult = cloudinary.Upload(hUploadParams);
                    Episode.VideoUrl = hUploadResult.SecureUrl.ToString();
                }
                var b = db.Animes.Find(Episode.AnimeId);
                NotificationView a = new NotificationView
                {
                    AnimeId = Episode.AnimeId,
                    AnimeName = b.AnimeName,
                    ImageVUrl = b.ImageVUrl,
                    Episode = Episode.Ep,
                    PostingDate = Episode.PostingDate,
                    Title = Episode.Title,
                    Permission = b.Permission,
                };
                db.Episodes.Add(Episode);
                db.SaveChanges();
                _backgroundJobClient.Schedule<EpisodeController>(x => x.AddNewEpisodes(a), Episode.PostingDate);
                //await AddNewEpisode(a);
                return RedirectToAction("EpisodeList" , new {id = Episode.AnimeId});
            }
            return View(Episode);
        }
        public void AddNewEpisodes(NotificationView a)
        {
             AddNewEpisode(a);           
        }

        public async Task AddNewEpisode(NotificationView newEpisode)
        {
            // Thêm tập phim mới vào cơ sở dữ liệu
            // ...
            var a = newEpisode;
            // Gửi thông báo đến các client
            await _hubContext.Clients.All.SendAsync("ReceiveNewEpisodeNotification", newEpisode);
        }
        [AuthForAdmin]
        [Route("admin/Episodeedit")]
        [HttpGet]
        public IActionResult EpisodeEdit(string id)
        {
            var a = db.Episodes.Where(x => x.EpisodeId == id).FirstOrDefault();
            return View(a);
        }
        [AuthForAdmin]
        [Route("Episodeedit")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult EpisodeEdits(Episode Episode, IFormFile video)
        {
            ModelState.Remove("video");
            if (ModelState.IsValid)
            {
                if (video != null )
                {
                    Account account = new Account(
                    "dbpbkj4pg",
                    "718584524965961",
                    "exe6MST-mc9nLkpubAWeazM7gLI");
                    Cloudinary cloudinary = new Cloudinary(account);
                    cloudinary.Api.Secure = true;
                    httpClient.Timeout = TimeSpan.FromMinutes(5);
                    using (var hStream = video.OpenReadStream())
                    {
                        var hUploadParams = new VideoUploadParams()
                        {
                            File = new FileDescription(video.FileName, hStream),
                            PublicId = "DATN/Anime/" + Episode.AnimeId.ToString() + "/Episode/ep" + Episode.Ep.ToString() + "/" + Episode.Ep.ToString() + Episode.AnimeId.ToString(),
                            Overwrite = true,
                        };
                        var hUploadResult = cloudinary.Upload(hUploadParams);
                        Episode.VideoUrl = hUploadResult.SecureUrl.ToString();
                    }
                }
                db.Entry(Episode).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("EpisodeList", new { id = Episode.AnimeId });
            }
            return RedirectToAction("EpisodeEdit", new { id = Episode.EpisodeId });
        }
        [AuthForAdmin]
        [Route("Episodedelete")]
        [HttpGet]
        public IActionResult EpisodeDelete(string id)
        {
            AutoCode at = new AutoCode();
            Account account = new Account(
                "dbpbkj4pg",
                "718584524965961",
                "exe6MST-mc9nLkpubAWeazM7gLI");
            Cloudinary cloudinary = new Cloudinary(account);
            cloudinary.Api.Secure = true;
            var views = db.Views.AsNoTracking().Where(x => x.EpisodeId == id).ToList();
            if (views.Any())
            {
                db.RemoveRange(views);
            }
            var cmts = db.Comments.AsNoTracking().Where(x => x.EpisodeId == id).ToList();
            if (cmts.Any())
            {
                db.RemoveRange(cmts);
            }
            var ep = db.Episodes.AsNoTracking().Where(x=>x.EpisodeId == id).FirstOrDefault();
            var publicId = at.ExtractPathFromUrl(ep.VideoUrl);
            var deletionParams = new DeletionParams(publicId)
            {
                ResourceType = ResourceType.Video
            };
            var deletionResult = cloudinary.Destroy(deletionParams);
            db.Remove(db.Episodes.Find(id));
            db.SaveChanges();

            return RedirectToAction("EpisodeList", new { id = ep.AnimeId });
        }
        
    }
}

DATNWEB/Areas/Admin/Views/Episode/EpisodeEdit.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@model DATNWEB.Models.Episode;
@{
    ViewData["Title"] = "EpisodeEdit";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="card">
    <div class="card-body">
        <h4 class="card-title">Add Episode</h4>
        <form method="post" action="@Url.Action("EpisodeEdits", "Episode")" class="forms-sample" enctype="multipart/form-data">
            @Html.AntiForgeryToken()
            <div class="form-group">
                <label>Episode ID</label>
                <input type="text" class="form-control" asp-for="EpisodeId" placeholder="ID" value="@Model.EpisodeId" readonly>
            </div>
            <div class="form-group">
                <label>Anime</label>
                <input type="text" class="form-control" asp-for="AnimeId" placeholder="ID" value="@Model.AnimeId" readonly>
            </div>
            <div class="form-group">
                <label>Title</label>
                <input type="text" class="form-control" asp-for="Title" placeholder="Name">
            </div>
            <div class="form-group">
                <label>Total episode</label>
                <input type="number" class="form-control" asp-for="Ep" value="@Model.Ep" readonly>
            </div>
            <div class="form-group">
                <label>Posting Date</label>
                <input asp-for="PostingDate" type="datetime-local" class="form-control" />
            </div>
            <input type="text" asp-for="VideoUrl" value="@Model.VideoUrl" hidden />
            <div class="form-group">
                <label>Video</label>               
                <input type="file" class="form-control" name="video">
            </div>

            <button type="submit" class="btn btn-gradient-primary me-2">Submit</button>
            <a class="btn btn-light" href="/admin/Episode">Cancel</a>
        </form>
    </div>
</div>

DATNWEB/Areas/Admin/Views/Episode/EpisodeList.cshtml
@using DATNWEB.Models;
@using X.PagedList.Mvc.Core;
@using X.PagedList.Web.Common;
@model X.PagedList.IPagedList<Episode>;
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@{
    ViewData["Title"] = "EpisodeList";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

@if (TempData["DeleteError"] != null)
{
    <div class="alert alert-danger" role="alert">
        @TempData["DeleteError"]
    </div>
}
<div class="card mb-4">
    <div class="card-header">
        <div class="d-flex justify-content-between align-items-center">
            <div>
                <i class="fas fa-table me-1"></i>
                <span class="fw-bold">Episode List</span>
            </div>
            <div>
                <a class="btn btn-primary" asp-action="EpisodesAdd" asp-route-ani="@ViewBag.AnimeId">Create New</a>
            </div>
        </div>
    </div>

    <div class="card-body">
        <table class="table table-bordered">
            <thead class="thead-dark">
                <tr>
                    <th>Anime Name</th>
                    <th>Episode</th>
                    <th>Title</th>
                    <th>Posting date</th>
                    <th></th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @if (Model.Count == 0)
                {
                    <tr>
                        <td colspan="6" style="text-align: center;">
                            No Data
                        </td>

                    </tr>
                }
                else
                {
                    @foreach (var item in Model)
                    {
                        QlPhimAnimeContext db = new QlPhimAnimeContext();
                        var name = db.Animes.Find(item.AnimeId);

                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => name.AnimeName)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Ep)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Title)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.PostingDate)
                            </td>
                            <td>
                                <a class="btn btn-primary" asp-action="EpisodeEdit" asp-route-id="@item.EpisodeId">Edit</a>
                            </td>
                            <td>
                                <a class="btn btn-danger" asp-action="EpisodeDelete" asp-route-id="@item.EpisodeId">Delete</a>
                            </td>
                        </tr>
                    }
                }

            </tbody>
        </table>
        @if (Model.PageCount > 1)
        {
            <div class="datatable-pagination">
                @Html.PagedListPager(Model, page => Url.Action("PackageList", new { page = page }), PagedListRenderOptions.ClassicPlusFirstAndLast)
            </div>
        }
    </div>
</div>

<div>
    <a class="btn btn-primary" href="/admin/anime">Anime List</a>
</div>

DATNWEB/Areas/Admin/Views/Episode/EpisodesAdd.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@model DATNWEB.Models.Episode;
@{
    ViewData["Title"] = "EpisodesAdd";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="card">
    <div class="card-body">
        <h4 class="card-title">Add Episode</h4>
        <form method="post" action="/Episodeadds" class="forms-sample" enctype="multipart/form-data">
            @Html.AntiForgeryToken()
            <div class="form-group">
                <label>Episode ID</label>
                <input type="text" class="form-control" asp-for="EpisodeId" placeholder="ID" value="@Model.EpisodeId" readonly>
            </div>
            <div class="form-group">
                <label>Anime</label>
                <input type="text" class="form-control" asp-for="AnimeId" placeholder="ID" value="@Model.AnimeId" readonly>
            </div>
            <div class="form-group">
                <label>Title</label>
                <input type="text" class="form-control" asp-for="Title" placeholder="Name">
            </div>
            <div class="form-group">
                <label>Total episode</label>
                <input type="number" class="form-control" asp-for="Ep" value="@Model.Ep" readonly>
            </div>
            <div class="form-group">
                <label>Posting Date</label>
                <input id="datetime-local-input" asp-for="PostingDate" type="datetime-local" class="form-control" />
            </div>
            <div class="form-group">
                <label>Video</label>
                <input type="file" class="form-control" name="video" accept=".mp4, .avi, .wmv, .mov, .flv, .mp3" onchange="validateVideo(this)">
                <span id="errorImage" class="text-danger"></span>
                @Html.ValidationMessage("video",new { @class = "text-danger" })
            </div>

            <button type="submit" class="btn btn-gradient-primary me-2">Submit</button>
            <a class="btn btn-light" href="/admin/Episode">Cancel</a>
        </form>
    </div>
</div>

<script>
    document.addEventListener('DOMContentLoaded', (event) => {
        var currentDate = new Date();
        // Lấy thời gian hiện tại UTC
        var utcTime = currentDate.getTime() + (currentDate.getTimezoneOffset() * 60000);
        // Tạo đối tượng Date mới với UTC+7
        var utcPlus7 = new Date(utcTime + (7 * 60 * 60000));
        // Trích xuất các thành phần thời gian
        var year = utcPlus7.getFullYear();
        var month = utcPlus7.getMonth() + 1; // Tháng bắt đầu từ 0
        var day = utcPlus7.getDate();
        var hours = utcPlus7.getHours();
        var minutes = utcPlus7.getMinutes();
        // Định dạng lại thời gian
        var formattedDateTime = year + '-' + pad(month) + '-' + pad(day) + 'T' + pad(hours) + ':' + pad(minutes);
        // Đặt giá trị cho input
        document.getElementById('datetime-local-input').value = formattedDateTime;
    });
    // Hàm để thêm số 0 vào trước các số có một chữ số
    function pad(number) {
        if (number < 10) {
            return '0' + number;
        }
        return number;
    }
    function validateVideo(input) {
        var errorSpan = document.getElementById("errorImage");
        var allowedExtensions = ['mp4', 'avi', 'wmv', 'mov', 'flv' , 'mp3'];
        var fileExtension = input.files[0].name.split('.').pop().toLowerCase();
        if (allowedExtensions.indexOf(fileExtension) === -1) {
            errorSpan.textContent = "Vui lòng chọn một tệp video có định dạng hợp lệ (mp4, avi, wmv, mov, flv, mp3)!";
            input.value = ''; // Xóa file đã chọn để người dùng chọn lại
        }
    }

</script>